# Generated by Django 2.1.7 on 2019-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cover',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
