# Generated by Django 2.1.7 on 2019-04-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_room_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='room',
        ),
    ]
